### ISSUE TITLE
Daiquiri/Userquery Devcontainers

### ISSUE THREAD

**Issue by glaubervila** [linea-it/lsp_daiquiri#1]
Configurar o ambiente de desenvolvimento utilizando devcontainers
```[tasklist]
### Tasks
- [x] Organizar o diretório, separando os arquivos de configuração por ambiente.  (Local, Production)
- [x] Adicionar instruções de instalação no README
- [x] Adicionar Tabelas/Dados de exemplo ( DES DR2, GAIA DR2 )
- [x] Configurar o ambiente de desenvolvimento utilizando devcontainer
- [x] Configurar Pre-Commit
- [x] Configurar Github Actions para rodar o Pre-Commit
```

**Comment by glaubervila** [comment]
@gschwend @ndmallmann Finalizei essa tarefa, não marquei como PR pq ficaria confuso explicar o clone e mudar o brach. 
Então já fiz o merge logo em main. 
Para validar, basta seguir os passos do README.md e seguir o processo todo para ter o ambiente local funcionando. 

https://github.com/linea-it/lsp_daiquiri

Ficou falando configurar o github actions. criei uma issue nova separada.
