### ISSUE TITLE
Atualização do daiquiri

### ISSUE THREAD

**Issue by gschwend** [linea-it/lsp_daiquiri#42]
```[tasklist]
### Tasks
- [x] Atualizar lista de dependencias
- [x] Atualizar a biblioteca daiquiri
- [x] Corrigir bug referente nova funcionalidade  https://github.com/django-daiquiri/daiquiri/pull/200
- [x] Corrigir problemas nos templates base
```

**Comment by luiz-nicolaci** [comment]
@ndmallmann algum progresso ?

**Comment by ndmallmann** [comment]
> @ndmallmann algum progresso ?

De acordo com o @glaubervila , foram feitas as correções do dev container e organização do diretório do projeto para permitir atualizações.

Falta atualizar o pacote e testar.
