### ISSUE TITLE
Páginas de Datasets

### ISSUE THREAD

**Issue by gschwend** [linea-it/lsp_daiquiri#66]
```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/lsp_daiquiri/issues/67
- [x] Criar menu "Data"
- [x] Criar duas páginas: DES DR2 e Gaia DR3
- [x] Importar conteúdo do repo idac_dw
```
