### ISSUE TITLE
Autenticação SAML utilizando djangosaml2

### ISSUE THREAD

**Issue by glaubervila** [linea-it/lsp_daiquiri#68]
```[tasklist]
### Tasks
- [ ] Remover a biblioteca Shibboleth e suas customizações. 
- [ ] Instalar a biblioteca [djangosaml2](https://github.com/IdentityPython/djangosaml2) e suas dependencias. 
- [ ] Configurar ambiente de dev 
- [ ] Atualizar documentação.
```

**Comment by deborajanini** [comment]
@glaubervila vaai ter documentação? Pois iria mover hoje para o status do infax
