### ISSUE TITLE
Habilitar páginas de metadata

### ISSUE THREAD

**Issue by glaubervila** [linea-it/lsp_daiquiri#71]
O Daiquiri possui páginas auto geradas com as informações dos schemas/tabelas. 
é necessário apenas criar o menu com a lista de schemas, e preencher os metadados.

Exemplo de uma página de metadata https://gaia.aip.de/metadata/gaiafpr/

```[tasklist]
### Tasks
- [x] Criar menu para os schemas e tabelas gaia e des
- [x] Preencher minimanente os metadados para as tabelas do des e do gaia.
- [x] Incluir os metadados no conjunto de dados iniciais da aplicação.
```
