### ISSUE TITLE
Text for User-Query pages

### ISSUE THREAD

**Issue by jandsonrj** [linea-it/lsp_daiquiri#74]
Contactar @Gomides -  Mayara Gomides

```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/lsp_daiquiri/issues/75
- [ ] https://github.com/linea-it/lsp_daiquiri/issues/76
- [ ] https://github.com/linea-it/lsp_daiquiri/issues/77
- [ ] https://github.com/linea-it/lsp_daiquiri/issues/78
- [ ] https://github.com/linea-it/lsp_daiquiri/issues/79
- [ ] https://github.com/linea-it/lsp_daiquiri/issues/80
```

**Comment by jandsonrj** [comment]
All tasks in the issue have been completed.
