### ISSUE TITLE
daiquiri home page

### ISSUE THREAD

**Issue by jandsonrj** [linea-it/lsp_daiquiri#75]
```[tasklist]
### Tasks
- [x] Call to action
- [x] Main paragraph about the user query https://docs.linea.org.br/sci-platforms/user_query.html
- [x] Short description for action buttons
- [x] Social media on banner (Youtube, TwitterX, Github and Instagram)
- [x] Footer with LIneA data, similar to Gaia ?
```
