### ISSUE TITLE
Metadados para o schema do Gaia

### ISSUE THREAD

**Issue by jandsonrj** [linea-it/lsp_daiquiri#76]
```[tasklist]
### Tasks
- [x] Página do Schema - (https://gaia.aip.de/metadata/gaiadr3/)
- [x] Página da Tabela DR3 - (https://gaia.aip.de/metadata/gaiadr3/gaia_source/)
- [x] Colunas da Tabela DR3 - (Unit, Description and UCDs with ';')
```

**Comment by gschwend** [comment]
@jandsonrj essa está feita, certo?

**Comment by jandsonrj** [comment]
> @jandsonrj essa está feita, certo?

se não me engano ficou faltando completar 'Colunas da Tabela DR3 - (Unit, Description and UCDs with ';')'
