### ISSUE TITLE
Metadados para o schema DES

### ISSUE THREAD

**Issue by jandsonrj** [linea-it/lsp_daiquiri#77]
Pegar esses conteúdos com a @gschwend ou o @adrianopieres, exemplo de uso [GAIA](https://gaia.aip.de/metadata/gaiadr3/gaia_source/)

```[tasklist]
### Tasks
- [x] Página do Schema DES DR2 - (https://userquery-dev.linea.org.br/metadata/des_dr2/)
- [x] Página da Tabela Coadd Objects - (https://gaia.aip.de/metadata/gaiadr3/gaia_source/)
- [x] Colunas da Tabela Coadd Objects - (Unit, Description and UCDs with ';')
- [x] Precisa do parágrafo para usar na atribuição/citação
- [x] Precisa do link do DOI
```

**Comment by gschwend** [comment]
@jandsonrj essa está feita, certo?

**Comment by jandsonrj** [comment]
> @jandsonrj essa está feita, certo?

essa também falta: Colunas da Tabela Coadd Objects - (Unit, Description and UCDs with ';'), acho que o adriano ficou de mandar o documento para eu preencher.
