### ISSUE TITLE
Documentation about integration User-Query + Target Viewer 

### ISSUE THREAD

**Issue by jandsonrj** [linea-it/lsp_daiquiri#95]
```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/lsp_daiquiri/issues/111
- [ ] https://github.com/linea-it/jupyterhub-tutorial/issues/30
- [x] update seção Overview
- [ ] https://github.com/linea-it/lsp_daiquiri/issues/117
- [x] ADQL and PostgreSQL
```

**Comment by adrianopieres** [comment]
Pessoal, estou com um blocker que é o nome do site para poder fazer os vídeos. Preciso que o site esteja funcionando com o endereço final para poder aparecer no vídeo. Senão ele aparece como *-dev, que não é o que queremos.

**Comment by gschwend** [comment]
Oi @adrianopieres, que tal fazer a captura da tela com um corte retangular pegando só o conteúdo dentro do navegador, sem pegar a parte com a URL? O que queremos mostrar é o funcionamento dos botões... acho que a URL não precisa aparecer.  Eu fiz assim em um dos vídeos antigos do portal: https://youtu.be/IcCk0MYhy-E?feature=shared

**Comment by adrianopieres** [comment]
É uma possibilidade @gschwend . De certa forma perde um pouco da informação, pois não aparece também para os outros acessos da página, mas dá pra configurar o soft de gravação para pegar apenas a parte abaixo do endereço da página.

**Comment by gschwend** [comment]
Eu acho válido, ainda mais se considerarmos que a URL pode mudar a médio prazo. Assim vc não precisa fazer nenhuma errata se mudar a URL. Essa informação pode ir no campo de descrição do vídeo, que é facimlente atualizada depois.

**Comment by adrianopieres** [comment]
@glaubervila @gschwend Meu receio maior é alguma mudança principalmente nas páginas iniciais e nos botões para fazer o vídeo, assim como alguns problemas iniciais. Jà posso fazer o vídeo sabendo que não haverá grandes alterações na página?
Acabei de efetuar um teste e dentro do target viewer a imagem não aparece mais depois de aplicado um filtro para os targets (fiz uma seleção básica em RA>certo valor). Pode ver isso @glaubervila ?

**Comment by adrianopieres** [comment]
Um dos problemas é que o link das páginas (tipo quando passo o mouse por cima do SkyViewer) é visualizado embaixo também, o que pode levar a informações erradas sobre a localização da página... Daí teria que cortar embaixo também, o que não sei se seria bom gerar um vídeo cortado em cima e embaixo...

**Comment by adrianopieres** [comment]
Além disso na página de entrada está como development. Não sei se essas correções poderiam ser aproveitadas para gerar issues de forma à página já ficar com aspecto de final...

**Comment by gschwend** [comment]
Concentra nos textos por favor e deixemos os vídeos para depois. Ajustei as prioridades no board do projeto de acordo.

**Comment by adrianopieres** [comment]
Seguem alguns textos em que fiz modificações. Acho que o melhor para implementar esse novo texto é comparar com o que está lá (para seguir o mesmo formato de subtítulos, hiperlinks e mais).
Basicamente revisei o texto, troquei GAIA@AIP por Linea@userquery, removi algumas funcionalidades que não estão disponíveis (como passar o mouse por cima das tabelas para ver a descrição, uso do Vizier, etc.)
No volume da tabela devem ser colocados os valores em TB (adicionei apenas ???), e a do 2MASS precisa do nome da tabela também.
@jandsonrj : preciso de alguma ajuda sobre as figuras que devem estar presentes em https://userquery-dev.linea.org.br/cms/services/scripted-access/ . Elas vão estar presentes aqui no userquery? Também sobre todo o esquema do pyvo, se é esse o oficial e tal. Lembro que eu tinha feito testes e um que havia no astropy que tinha funcionado. Acho melhor marcar uma conversa para ver estes detalhes.
Texto em:
https://userquery-dev.linea.org.br/cms/services/query-interface/:
"""
Query interface – explained
Here you will find a detailed explanation to the query interface.

Submit SQL Query
Linea@userquery hosts the data from astromical survey data releases in a PostgresQL database. The data can be queried directly using the Astronomical Data Query Language (ADQL) or the Postgres flavour of SQL (Structured Query Language).

Submit a new job
Open the Query interface in a browser window.
Insert your SQL query in the text area SQL query or choose an example query from the Examples tab in the top-right of the interface (just double click on one of them) above the text area.
Give the result table a name.
Choose either ADQL or PostgreSQL. Choose one of the Queues.
Click Submit new SQL Query button to submit your job.
The job is submitted into one of the job Queue: 30 seconds for a short test query, 5 minute for longer ones, and for long running queries, 2h.

Database browser
Above the text area, you find the Schema and the Columns browser. It is useful to find out which columns exist for which table in which data release. You will find your user database and your uploaded tables in the browser. You can join tables from your private database with each other or the datasets.

Results of a query job
You can view your results by clicking on the table name for your job in the Job list and then choosing the Results table tab.

Back in the Job overview tab, you can review again which query was executed, its Job parameters such as time and size of the resulting tables etc.

It is also possible to Rename the job’s result table or run id or to Archive the job completely using the links just below the Job parameters.

The Plot tab provides a very simple plot-interface for numeric columns.

The results can be downloaded via the Download tab. Download provides various formats. Currently, CSV or IVOA VOTable XML files are available.

Job list
After a successful job submission, your job will appear in the Job list bar on the left. Its name corresponds to the result-table name, which is either the current time stamp or a name that you have provided in the Table name field.

Private cross-matching and your query archive
The Query interface allows to upload your own VOTables into your private user database at Linea@userquery.

The uploaded tables can be queried like any other database using SELECT statements. You can also browse the available tables and their columns using the “Database Browser” below the Query Form or referring to UPLOAD_TABLES. where is the name of the table to provided during upload.
"""
Texto em:
https://userquery-dev.linea.org.br/cms/services/direct-download/

"""
Direct Download
Here you can download various tables directly:

Data Release	table	size
DES DR2         main            ??? TB
GAIA DR3	gaia_source	??? TB
2MASS	??????	??? TB
In case you need to download further tables not listed here please contact us.

Download the results of a request
Please use the Query interface to submit your search. All result tables can be downloaded in different formats, including CSV as listed on the Download tab of the Query interface.

Download formats

Comma-separated Values	A text file with a line for each row of the table. The fields are delimited by a comma and enclosed by double quotes. Use this option for a later import into a spreadsheet application or a custom script. Use this option if you are unsure what to use.
IVOA VOTable XML file	A XML file using the IVOA VOTable format. Use this option if you intend to use VO compatible software to further process the data.
FITS Standard format for astronomical sources.

"""

**Comment by gschwend** [comment]
@adrianopieres @kirmairlima 
FYI: subdividi esse issue em dois (ver tasklist na descrição), o Adriano já estava providenciando o texto para exibir no user query e eu vou ficar com a parte do jupyter notebook de tutorial.

**Comment by adrianopieres** [comment]
Complemento o que foi passado anteriormente:

GAIA DR3:

If you have used Gaia DR3 data in your research from this site, please use the following acknowledgement:

This work has made use of data from the European Space Agency (ESA) mission Gaia (https://www.cosmos.esa.int/gaia), processed by the Gaia Data Processing and Analysis Consortium (DPAC, https://www.cosmos.esa.int/web/gaia/dpac/consortium). Funding for the DPAC has been provided by national institutions, in particular the institutions participating in the Gaia Multilateral Agreement.

Database access and other data services are provided by the Associação Laboratório Interinstitucional de e-Astronomia(LIneA) with the financial support from INCT do e-Universo (Processo n.º 465376/2014-2).

DES DR2:

If you have used DES DR2 data in your research from this site, please use the following acknowledgement:

This project used public archival data from the Dark Energy Survey (DES). Funding for the DES Projects has been provided by the U.S. Department of Energy, the U.S. National Science Foundation, the Ministry of Science and Education of Spain, the Science and Technology Facilities Council of the United Kingdom, the Higher Education Funding Council for England, the National Center for Supercomputing Applications at the University of Illinois at Urbana–Champaign, the Kavli Institute of Cosmological Physics at the University of Chicago, the Center for Cosmology and Astro-Particle Physics at the Ohio State University, the Mitchell Institute for Fundamental Physics and Astronomy at Texas A&M University, Financiadora de Estudos e Projetos, Fundação Carlos Chagas Filho de Amparo à Pesquisa do Estado do Rio de Janeiro, Conselho Nacional de Desenvolvimento Científico e Tecnológico and the Ministério da Ciência, Tecnologia e Inovação, the Deutsche Forschungsgemeinschaft and the Collaborating Institutions in the Dark Energy Survey.

The Collaborating Institutions are Argonne National Laboratory, the University of California at Santa Cruz, the University of Cambridge, Centro de Investigaciones Enérgeticas, Medioambientales y Tecnológicas–Madrid, the University of Chicago, University College London, the DES-Brazil Consortium, the University of Edinburgh, the Eidgenössische Technische Hochschule (ETH) Zürich, Fermi National Accelerator Laboratory, the University of Illinois at Urbana-Champaign, the Institut de Ciències de l'Espai (IEEC/CSIC), the Institut de Física d'Altes Energies, Lawrence Berkeley National Laboratory, the Ludwig-Maximilians Universität München and the associated Excellence Cluster Universe, the University of Michigan, the National Optical Astronomy Observatory, the University of Nottingham, the Ohio State University, the OzDES Membership Consortium, the University of Pennsylvania, the University of Portsmouth, SLAC National Accelerator Laboratory, Stanford University, the University of Sussex, and Texas A&M University.

Based in part on observations at Cerro Tololo Inter-American Observatory, National Optical Astronomy Observatory, which is operated by the Association of Universities for Research in Astronomy (AURA) under a cooperative agreement with the National Science Foundation.

Database access and other data services are provided by the Associação Laboratório Interinstitucional de e-Astronomia(LIneA) with the financial support from INCT do e-Universo (Processo n.º 465376/2014-2).

2MASS:

This publication makes use of data products from the Two Micron All Sky Survey, which is a joint project of the University of Massachusetts and the Infrared Processing and Analysis Center/California Institute of Technology, funded by the National Aeronautics and Space Administration and the National Science Foundation.

Database access and other data services are provided by the Associação Laboratório Interinstitucional de e-Astronomia(LIneA) with the financial support from INCT do e-Universo (Processo n.º 465376/2014-2).
